#!/usr/bin/env bash
# quality-center.sh — worktree logic for the quality-center project

QC_DIR="$SCORTAIX_PROJECTS_DIR/quality-center"

qc_tree() {
    local branch="$1"
    local worktree_dir
    worktree_dir=$(_worktree_dir "quality-center" "$branch")

    local create_result instance offset
    if create_result=$(_worktree_create "$QC_DIR" "$worktree_dir" "$branch"); then
        read -r instance offset <<< "$create_result"
    else
        return 0
    fi

    local pgport=$(( 55432 + offset ))
    local conflict
    conflict=$(docker ps -q --filter "publish=$pgport")
    if [[ -n "$conflict" ]]; then
        step "Stopping container already bound to port $pgport"
        docker stop "$conflict" >/dev/null
    fi

    step "Writing .envrc"
    cat > "$worktree_dir/.envrc" << EOF
# Auto-generated by scortaix — do not commit (already gitignored).
# Instance $instance — port offset +$offset.

source .venv/bin/activate
unset PS1

export PGPORT=$(( 55432 + offset ))
export DJANGO_PORT=$(( 8000 + offset ))
export VITE_PORT=$(( 5173 + offset ))
export DJANGO_SESSION_COOKIE_NAME=sessionid-$(( 8000 + offset ))
EOF

    # Honcho requires a .env file to exist even if empty
    touch "$worktree_dir/.env"

    step "Python dependencies (uv sync)"
    uv sync --project "$worktree_dir"

    step "Pre-commit hooks"
    (cd "$worktree_dir" && uv run pre-commit install)

    step "Git config"
    git -C "$worktree_dir" config --local include.path ../.gitconfig

    step "JS dependencies (pnpm install)"
    (cd "$worktree_dir/frontend" && pnpm install)

    step "direnv allow"
    direnv allow "$worktree_dir"

    step "Starting services for database setup"
    local make_run_log="/tmp/scortaix-qc-setup-$$.log"
    setsid bash -c "cd '$worktree_dir' && source .envrc && make run" \
        > "$make_run_log" 2>&1 &
    local make_run_pid=$!

    step "Waiting for PostgreSQL to be ready"
    local attempt=0
    until pg_isready -h 127.0.0.1 -p "$pgport" -q 2>/dev/null; do
        sleep 1
        attempt=$(( attempt + 1 ))
        if (( attempt > 90 )); then
            kill -- -"$make_run_pid" 2>/dev/null || true
            error "PostgreSQL did not start after 90s — logs at $make_run_log"
        fi
    done

    step "Setting up local database"
    local setup_ok=0
    if (cd "$worktree_dir" && source .envrc && ./setup-local-db.sh); then
        setup_ok=1
    fi

    step "Stopping services"
    kill -- -"$make_run_pid" 2>/dev/null || true
    wait "$make_run_pid" 2>/dev/null || true
    rm -f "$make_run_log"

    [[ $setup_ok -eq 1 ]] || error "Database setup failed"

    success "Worktree ready!"
    echo ""
    printf "  %-22s http://localhost:%d\n"  "Django:"     $(( 8000  + offset ))
    printf "  %-22s http://localhost:%d\n"  "Vite dev:"   $(( 5173  + offset ))
    printf "  %-22s localhost:%d\n"         "PostgreSQL:" $(( 55432 + offset ))
    echo ""
    echo "  Next: make run"

    _worktree_write_last_dir "$worktree_dir"
}

qc_clean() {
    local branch="$1"
    local worktree_dir
    worktree_dir=$(_worktree_dir "quality-center" "$branch")

    _worktree_confirm_clean "$worktree_dir" "$branch" "Postgres"

    step "Stopping Docker containers"
    local pgport
    pgport=$(grep 'export PGPORT=' "$worktree_dir/.envrc" 2>/dev/null | cut -d= -f2 || true)
    if [[ -n "$pgport" ]]; then
        (cd "$worktree_dir" && PGPORT="$pgport" docker compose down -v)
        success "Containers stopped"
    else
        warn "Could not read PGPORT from .envrc — containers may still be running"
    fi

    _worktree_finalize_clean "$QC_DIR" "$worktree_dir" "$branch"
}
