#!/usr/bin/env bash
# sensei.sh — worktree logic for the sensei/spark project

SENSEI_DIR="$SCORTAIX_PROJECTS_DIR/sensei"

sensei_tree() {
    local branch="$1"
    local worktree_dir
    worktree_dir=$(_worktree_dir "sensei" "$branch")

    local create_result instance offset
    if create_result=$(_worktree_create "$SENSEI_DIR" "$worktree_dir" "$branch"); then
        read -r instance offset <<< "$create_result"
    else
        return 0
    fi

    step "Writing .envrc"
    cat > "$worktree_dir/.envrc" << EOF
# Auto-generated by scortaix — do not commit (already gitignored).
# Instance $instance — port offset +$offset.

source .venv/bin/activate
unset PS1

export COMPOSE_PROJECT_NAME=sensei-$instance
export REDIS_CONTAINER_NAME=redis-$instance
export POSTGRES_CONTAINER_NAME=postgres-$instance
export ADMINER_CONTAINER_NAME=adminer-$instance

export REDIS_PORT=$(( 6379 + offset ))
export POSTGRES_PORT=$(( 5432 + offset ))
export ADMINER_PORT=$(( 8080 + offset ))

export BIND_PORT=$(( 5000 + offset ))
export WEBSOCKET_PORT=$(( 12321 + offset ))
export CAMERA_WEBSOCKET_PORT=$(( 4000 + offset * 4 ))
export DEV_FRONTEND_PORT=$(( 3000 + offset ))

export DATABASE_PORT=$(( 5432 + offset ))
EOF

    step "Python dependencies (uv sync --inexact --extra ml)"
    uv sync --inexact --extra ml --project "$worktree_dir"

    step "JS dependencies (pnpm install)"
    (cd "$worktree_dir" && pnpm install)

    step "ML perf images"
    (cd "$worktree_dir" && uv run spark/backend/emulated_images/download_ml_perf_images.py)

    step "Pre-commit hooks"
    (cd "$worktree_dir" && uv run pre-commit install --allow-missing-config)

    step "Git config"
    git -C "$worktree_dir" config --local include.path ../.gitconfig

    step "direnv allow"
    direnv allow "$worktree_dir"

    success "Worktree ready!"
    echo ""
    printf "  %-22s http://localhost:%d\n"  "Flask:"      $(( 5000  + offset ))
    printf "  %-22s ws://localhost:%d\n"    "WebSocket:"  $(( 12321 + offset ))
    printf "  %-22s ws://localhost:%d-%d\n" "Cam WS:"     $(( 4000 + offset * 4 )) $(( 4003 + offset * 4 ))
    printf "  %-22s http://localhost:%d\n"  "Vite dev:"   $(( 3000  + offset ))
    printf "  %-22s localhost:%d\n"         "PostgreSQL:" $(( 5432  + offset ))
    printf "  %-22s localhost:%d\n"         "Redis:"      $(( 6379  + offset ))
    echo ""
    echo "  Next: cd spark && docker-compose up -d && make dev-frontend"

    _worktree_write_last_dir "$worktree_dir"
}

sensei_clean() {
    local branch="$1"
    local worktree_dir
    worktree_dir=$(_worktree_dir "sensei" "$branch")
    local envrc="$worktree_dir/.envrc"

    _worktree_confirm_clean "$worktree_dir" "$branch" "Redis, Postgres, Adminer"

    if [[ -f "$envrc" ]]; then
        step "Stopping Docker containers"
        local redis_name postgres_name adminer_name
        redis_name=$(grep  'export REDIS_CONTAINER_NAME='    "$envrc" | cut -d= -f2)
        postgres_name=$(grep 'export POSTGRES_CONTAINER_NAME=' "$envrc" | cut -d= -f2)
        adminer_name=$(grep  'export ADMINER_CONTAINER_NAME='  "$envrc" | cut -d= -f2)
        for container in "$redis_name" "$postgres_name" "$adminer_name"; do
            [[ -n "$container" ]] && docker rm -f "$container" 2>/dev/null \
                && success "Removed $container"
        done
    fi

    _worktree_finalize_clean "$SENSEI_DIR" "$worktree_dir" "$branch"
}
